language: go

sudo: false

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - tip

before_install:
  - go get github.com/golang/lint/golint

before_script:
  - go vet ./...
  - golint ./...

script:
  - go test -v ./...
