// This file was automatically generated by codeform.
// DO NOT EDIT MANUALLY.
// Regenerate with `go generate`

package mocking

// MockedGreeter is a mock implementation of Greeter.
type MockedGreeter struct {
	// GreetFunc provides a mock implementation of Greet.
	GreetFunc func(name string) (string, error)
	// GreetCalls represents the number of times Greet was called.
	GreetCalls int
	// ResetFunc provides a mock implementation of Reset.
	ResetFunc func()
	// ResetCalls represents the number of times Reset was called.
	ResetCalls int
}

// Greet calls GreetFunc.
func (m *MockedGreeter) Greet(name string) (string, error) {
	if m.GreetFunc == nil {
		panic("call to MockedGreeter.Greet with nil GreetFunc")
	}
	m.GreetCalls++
	return m.GreetFunc(name)
}

// Reset calls ResetFunc.
func (m *MockedGreeter) Reset() {
	if m.ResetFunc == nil {
		panic("call to MockedGreeter.Reset with nil ResetFunc")
	}
	m.ResetCalls++
	m.ResetFunc()
}

// MockedSignoff is a mock implementation of Signoff.
type MockedSignoff struct {
	// SignoffFunc provides a mock implementation of Signoff.
	SignoffFunc func(name string) string
	// SignoffCalls represents the number of times Signoff was called.
	SignoffCalls int
}

// Signoff calls SignoffFunc.
func (m *MockedSignoff) Signoff(name string) string {
	if m.SignoffFunc == nil {
		panic("call to MockedSignoff.Signoff with nil SignoffFunc")
	}
	m.SignoffCalls++
	return m.SignoffFunc(name)
}
